services:
  api-consult:
    container_name: backend-api-service
    build:
      context: .
      dockerfile: Dockerfile
    image: api-consult:latest
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge