services:
  api-consult:
    container_name: backend-api-service
    build:
      context: .
      dockerfile: Dockerfile
    image: api-consult:latest
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge